----INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV2,SINAV3) VALUES (6,2,41,45,78)
--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3
--UPDATE TBLNOTLAR set DURUM=0 WHERE ORTALAMA<50
--UPDATE TBLNOTLAR set DURUM=1 WHERE ORTALAMA>50


--select Count(*) AS 'TOPLAM KAYIT' FROM TBLOGRENCILER
--SELECT COUNT(*) AS 'TOPLAM KISI' FROM TBLOGRENCILER WHERE OGRSEHIR='ADANA'

--SELECT SUM(SINAV1),SUM(SINAV2),SUM(SINAV3) FROM TBLNOTLAR
--SELECT AVG(SINAV1),AVG(SINAV2),AVG(SINAV3)  FROM TBLNOTLAR
--SELECT MAX(SINAV1) FROM TBLNOTLAR
--SELECT OGRCINSIYET,COUNT(*) AS 'TOPLAM' FROM TBLOGRENCILER GROUP BY OGRCINSIYET

--SELECT DURUM,COUNT(*) FROM TBLNOTLAR GROUP BY DURUM
--SELECT (OGRKULUP),COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP
--SELECT OGRSEHIR,COUNT(*) AS 'SAYI' FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2
--select durum,count(*) as'gecenler' from tblnotlar  group by durum  having durum=1 
--select durum,count(*) as'gecemeyenler' from tblnotlar  group by durum  having durum=0 
--select * from TBLOGRENCILER where OGRSEHIR  like  '%ana%'
--select * from TBLOGRENCILER where OGRSEHIR not like  '%a%'
--select distinct OGRSEHIR from TBLOGRENCILER
--select COUNT(distinct( OGRSEHIR) )from TBLOGRENCILER
--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER
--SELECT * FROM TBLOGRENCILER  ORDER BY OGRSEHIR DESC
--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER ORDER BY OGRKULUP DESC
--SELECT*FROM TBLOGRENCILER where OGRSEHIR like '%an_%' 
--SELECT*FROM TBLOGRENCILER where OGRAD like '[A,B]%' 
--SELECT TOP 3* FROM TBLOGRENCILER 
--SELECT TOP 3* FROM TBLOGRENCILER ORDER BY ogrýd DESC
--select top 40 percent * from TBLOGRENCILER
--select * from TBLOGRENCILER where OGRSEHIR='IZMIR' or OGRSEHIR='ankara' or OGRSEHIR='adana'
--select * from TBLOGRENCILER where OGRSEHIR in('IZMIR','ANKARA','ADANA') makes shorter and easier  not in shows which doesnt include
--select * from tblnotlar where ortalama between 50 and 100
--select * from TBLOGRENCILER where ograd between 'A' and 'N'  doesnt include second for exmpl N
--update TBLOGRENCILER set OGRKULUP=1 where OGRKULUP='BILISIM'






